# -*- coding: utf-8 -*-
"""NG_attn_Utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_2If_ce4F-sShzwLm-1fFY1ol1vs-56
"""

import os
import torch
import torch.optim as optim
from scipy.sparse import csr_matrix
import pandas as pd
import numpy as np
import random as rd
import scipy.sparse as sp
from time import time
import random
import matplotlib.pyplot as plt

from sklearn.metrics import roc_auc_score
np.set_printoptions(suppress=True)
import pickle
import multiprocessing
import heapq
import torch
import torch.nn as nn
import torch.nn.functional as F
# from google.colab import drive
# drive.mount('/content/drive/')
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def save_ckp(state, is_best, checkpoint_path, best_model_path):
    """
    state: checkpoint we want to save
    is_best: is this the best checkpoint; min validation loss
    checkpoint_path: path to save checkpoint
    best_model_path: path to save best model
    """
    f_path = checkpoint_path+'/current_checkpoint.pt'
    # save checkpoint data to the path given, checkpoint_path
    torch.save(state, f_path)
    # if it is a best model, min validation loss
    if False:
        best_fpath = best_model_path
        # copy that checkpoint file to best path given, best_model_path
        shutil.copyfile(f_path, best_fpath)

def recall(rank, ground_truth, N):
    return len(set(rank[:N]) & set(ground_truth)) / float(len(set(ground_truth)))


def precision_at_k(r, k):
    """Score is precision @ k
    Relevance is binary (nonzero is relevant).
    Returns:
        Precision @ k
    Raises:
        ValueError: len(r) must be >= k
    """
    assert k >= 1
    r = np.asarray(r)[:k]
    return np.mean(r)


def average_precision(r,cut):
    """Score is average precision (area under PR curve)
    Relevance is binary (nonzero is relevant).
    Returns:
        Average precision
    """
    r = np.asarray(r)
    out = [precision_at_k(r, k + 1) for k in range(cut) if r[k]]
    if not out:
        return 0.
    return np.sum(out)/float(min(cut, np.sum(r)))


def mean_average_precision(rs):
    """Score is mean average precision
    Relevance is binary (nonzero is relevant).
    Returns:
        Mean average precision
    """
    return np.mean([average_precision(r) for r in rs])


def dcg_at_k(r, k, method=1):
    """Score is discounted cumulative gain (dcg)
    Relevance is positive real values.  Can use binary
    as the previous methods.
    Returns:
        Discounted cumulative gain
    """
    #r = np.asfarray(r)[:k]
    r = np.asarray(r, dtype=float)[:k]
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.


def ndcg_at_k(r, k, ground_truth, method=1):
    """Score is normalized discounted cumulative gain (ndcg)
    Relevance is positive real values.  Can use binary
    as the previous methods.
    Returns:
        Normalized discounted cumulative gain

        Low but correct defination
    """
    GT = set(ground_truth)
    if len(GT) > k :
        sent_list = [1.0] * k
    else:
        sent_list = [1.0]*len(GT) + [0.0]*(k-len(GT))
    dcg_max = dcg_at_k(sent_list, k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max


def recall_at_k(r, k, all_pos_num):
    # if all_pos_num == 0:
    #     return 0
    #r = np.asfarray(r)[:k]
    r = np.asarray(r, dtype=float)[:k]
    return np.sum(r) / all_pos_num


def hit_at_k(r, k):
    r = np.array(r)[:k]
    if np.sum(r) > 0:
        return 1.
    else:
        return 0.

def F1(pre, rec):
    if pre + rec > 0:
        return (2.0 * pre * rec) / (pre + rec)
    else:
        return 0.

def AUC(ground_truth, prediction):
    try:
        res = roc_auc_score(y_true=ground_truth, y_score=prediction)
    except Exception:
        res = 0.
    return res

def ranklist_by_heapq(user_pos_test, test_items, rating, Ks):
    item_score = {}
    for i in test_items:
        item_score[i] = rating[i]

    K_max = max(Ks)
    K_max_item_score = heapq.nlargest(K_max, item_score, key=item_score.get)

    r = []
    for i in K_max_item_score:
        if i in user_pos_test:
            r.append(1)
        else:
            r.append(0)
    auc = 0.
    return r, auc

def get_auc(item_score, user_pos_test):
    item_score = sorted(item_score.items(), key=lambda kv: kv[1])
    item_score.reverse()
    item_sort = [x[0] for x in item_score]
    posterior = [x[1] for x in item_score]

    r = []
    for i in item_sort:
        if i in user_pos_test:
            r.append(1)
        else:
            r.append(0)
    auc = metrics.auc(ground_truth=r, prediction=posterior)
    return auc

def ranklist_by_sorted(user_pos_test, test_items, rating, Ks):
    item_score = {}
    for i in test_items:
        item_score[i] = rating[i]

    K_max = max(Ks)
    K_max_item_score = heapq.nlargest(K_max, item_score, key=item_score.get)

    r = []
    for i in K_max_item_score:
        if i in user_pos_test:
            r.append(1)
        else:
            r.append(0)
    auc = get_auc(item_score, user_pos_test)
    return r, auc

def get_performance(user_pos_test, r, auc, Ks):
    precision, recall, ndcg, hit_ratio = [], [], [], []

    for K in Ks:
        precision.append(precision_at_k(r, K))
        recall.append(recall_at_k(r, K, len(user_pos_test)))
        ndcg.append(ndcg_at_k(r, K, user_pos_test))
        hit_ratio.append(hit_at_k(r, K))

    return {'recall': np.array(recall), 'precision': np.array(precision),
            'ndcg': np.array(ndcg), 'hit_ratio': np.array(hit_ratio), 'auc': auc}


def test_one_user(x):
    # user u's ratings for user u
    rating = x[0]
    #uid
    u = x[1]
    #user u's items in the training set
    try:
        training_items = data_generator.train_items[u]
    except Exception:
        training_items = []
    #user u's items in the test set
    user_pos_test = data_generator.test_set[u]

    all_items = set(range(ITEM_NUM))

    test_items = list(all_items - set(training_items))

    if args.test_flag == 'part':
        r, auc = ranklist_by_heapq(user_pos_test, test_items, rating, Ks)
    else:
        r, auc = ranklist_by_sorted(user_pos_test, test_items, rating, Ks)

    return get_performance(user_pos_test, r, auc, Ks)


# def test(model, users_to_test, drop_flag=False, batch_test_flag=False):
#     import multiprocessing
#     cores = multiprocessing.cpu_count() // 2  # Use half the cores to be safe
#     pool = multiprocessing.Pool(cores)
#     Ks = [10]
#     result = {'precision': np.zeros(len(Ks)), 'recall': np.zeros(len(Ks)), 'ndcg': np.zeros(len(Ks)),
#               'hit_ratio': np.zeros(len(Ks)), 'auc': 0.}

#     pool = multiprocessing.Pool(cores)

#     u_batch_size = BATCH_SIZE * 2
#     i_batch_size = BATCH_SIZE

#     test_users = users_to_test
#     n_test_users = len(test_users)
#     n_user_batchs = n_test_users // u_batch_size + 1

#     count = 0

#     for u_batch_id in range(n_user_batchs):
#         start = u_batch_id * u_batch_size
#         end = (u_batch_id + 1) * u_batch_size

#         user_batch = test_users[start: end]

#         if batch_test_flag:
#             # batch-item test
#             n_item_batchs = ITEM_NUM // i_batch_size + 1
#             rate_batch = np.zeros(shape=(len(user_batch), ITEM_NUM))

#             i_count = 0
#             for i_batch_id in range(n_item_batchs):
#                 i_start = i_batch_id * i_batch_size
#                 i_end = min((i_batch_id + 1) * i_batch_size, ITEM_NUM)

#                 item_batch = range(i_start, i_end)

#                 if drop_flag == False:
#                     u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
#                                                                   item_batch,
#                                                                   [],
#                                                                   drop_flag=False)
#                     i_rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()
#                 else:
#                     u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
#                                                                   item_batch,
#                                                                   [],
#                                                                   drop_flag=True)
#                     i_rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()

#                 rate_batch[:, i_start: i_end] = i_rate_batch
#                 i_count += i_rate_batch.shape[1]

#             assert i_count == ITEM_NUM

#         else:
#             # all-item test
#             item_batch = range(ITEM_NUM)

#             if drop_flag == False:
#                 u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
#                                                               item_batch,
#                                                               [],
#                                                               drop_flag=False)
#                 rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()
#             else:
#                 u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
#                                                               item_batch,
#                                                               [],
#                                                               drop_flag=True)
#                 rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()

#         user_batch_rating_uid = zip(rate_batch.numpy(), user_batch)
#         batch_result = pool.map(test_one_user, user_batch_rating_uid)
#         count += len(batch_result)

#         for re in batch_result:
#             result['precision'] += re['precision']/n_test_users
#             result['recall'] += re['recall']/n_test_users
#             result['ndcg'] += re['ndcg']/n_test_users
#             result['hit_ratio'] += re['hit_ratio']/n_test_users
#             result['auc'] += re['auc']/n_test_users


#     assert count == n_test_users
#     pool.close()
#     return result