# -*- coding: utf-8 -*-
"""ngcg_with_attn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7f_SOS7QJhrHAPMuxX9hoeLrEJAexVb
"""

import os
import torch
import torch.optim as optim
from scipy.sparse import csr_matrix
import pandas as pd
import numpy as np
import random as rd
import scipy.sparse as sp
from time import time
import random
import matplotlib.pyplot as plt
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'  # so the exact line is revealed
import multiprocessing

from sklearn.metrics import roc_auc_score
np.set_printoptions(suppress=True)
import pickle
import multiprocessing
import heapq
import torch
import torch.nn as nn
import torch.nn.functional as F
import argparse
import sys
sys.path.append('/content/drive/MyDrive/CSPROJ/')
from ng_attn_utility import *
from tqdm import tqdm
class Data(object):
    def __init__(self, path, batch_size, attn_k=15):
        self.path = path
        self.batch_size = batch_size
        self.attn_k = attn_k

        train_file = os.path.join(path, 'train.txt')
        test_file = os.path.join(path, 'test.txt')

        self.n_users, self.n_items = 0, 0
        self.n_train, self.n_test = 0, 0
        self.neg_pools = {}
        self.exist_users = []

        self.train_items = {}
        self.item_to_users = {}

        # ==== Optional: Check shape of user/item attribute files ====
        user_feat_path = os.path.join(path, 'user_features.npy')
        item_feat_path = os.path.join(path, 'item_features.npy')
        self.user_feat_count = 0
        self.item_feat_count = 0

        if os.path.exists(user_feat_path):
            user_feats = np.load(user_feat_path)
            self.user_feat_count = user_feats.shape[0]

        if os.path.exists(item_feat_path):
            item_feats = np.load(item_feat_path)
            self.item_feat_count = item_feats.shape[0]

        # ==== Parse train.txt ====
        with open(train_file) as f:
            for l in f.readlines():
                if len(l) > 0:
                    l = l.strip('\n').split(' ')
                    uid = int(l[0])
                    items = [int(i) for i in l[1:]]
                    self.exist_users.append(uid)
                    self.n_users = max(self.n_users, uid)
                    self.n_items = max(self.n_items, max(items))
                    self.n_train += len(items)

                    self.train_items[uid] = items
                    for i in items:
                        self.item_to_users.setdefault(i, []).append(uid)

        # ==== Parse test.txt ====
        with open(test_file) as f:
            for l in f.readlines():
                if len(l) > 0:
                    l = l.strip('\n').split(' ')
                    uid = int(l[0])
                    self.n_users = max(self.n_users, uid)
                    try:
                        items = [int(i) for i in l[1:]]
                        self.exist_users.append(uid)
                        self.n_items = max(self.n_items, max(items))
                        self.n_test += len(items)
                    except Exception:
                        continue

        # ==== Final user/item count with padding ====
        self.n_users = max(self.n_users + 1, self.user_feat_count)
        self.n_items = max(self.n_items + 1, self.item_feat_count)

        print(f"🔧 Final n_users = {self.n_users}, n_items = {self.n_items}")

        # ==== Build neighbors ====
        # self.user_neighbors = self._build_neighbors(self.train_items, self.n_users, self.attn_k)
        # self.item_neighbors = self._build_neighbors(self.item_to_users, self.n_items, self.attn_k)

          # === Build padded neighbor matrices ===
        self.user_neighbors = self._build_neighbors(self.train_items, self.n_users, self.attn_k)
        self.item_neighbors = self._build_neighbors(self.item_to_users, self.n_items, self.attn_k)

        #self.print_statistics()
        print("\nSample user_neighbors:")
        for uid in range(min(5, self.n_users)):
            print(f"User {uid} → Items {self.user_neighbors[uid].tolist()}")

        print("\nSample item_neighbors:")
        for iid in range(min(5, self.n_items)):
            print(f"Item {iid} ← Users {self.item_neighbors[iid].tolist()}")



        self.print_statistics()

        self.R = sp.dok_matrix((self.n_users, self.n_items), dtype=np.float32)

        self.train_items, self.test_set = {}, {}
        with open(train_file) as f_train:
            with open(test_file) as f_test:
                for l in f_train.readlines():
                    if len(l) == 0:
                        break
                    l = l.strip('\n')
                    items = [int(i) for i in l.split(' ')]
                    uid, train_items = items[0], items[1:]

                    for i in train_items:
                        self.R[uid, i] = 1.
                        # self.R[uid][i] = 1

                    self.train_items[uid] = train_items

                for l in f_test.readlines():
                    if len(l) == 0: break
                    l = l.strip('\n')
                    try:
                        items = [int(i) for i in l.split(' ')]
                        try:
                            uid, test_items = items[0], items[1:]
                            self.test_set[uid] = test_items
                        except Exception:
                            continue

                    except Exception:
                        continue
    def _build_neighbors(self, mapping_dict, total_count, attn_k):
        neighbors = []
        for idx in range(total_count):
            ids = mapping_dict.get(idx, [])
            if len(ids) == 0:
                padded = [0] * attn_k
            elif len(ids) < attn_k:
                padded = ids + [ids[-1]] * (attn_k - len(ids))
            else:
                padded = ids[:attn_k]
            neighbors.append(padded)
        return torch.tensor(neighbors, dtype=torch.long)
    def get_adj_mat(self):
        try:
            t1 = time()
            adj_mat = sp.load_npz(self.path + '/s_adj_matx.npz')
            norm_adj_mat = sp.load_npz(self.path + '/s_norm_adj_matx.npz')
            mean_adj_mat = sp.load_npz(self.path + '/s_mean_adj_matx.npz')
            print('already load adj matrix', adj_mat.shape, time() - t1)

        except Exception:
            adj_mat, norm_adj_mat, mean_adj_mat = self.create_adj_mat()
            sp.save_npz(self.path + '/s_adj_mat.npz', adj_mat)
            sp.save_npz(self.path + '/s_norm_adj_mat.npz', norm_adj_mat)
            sp.save_npz(self.path + '/s_mean_adj_mat.npz', mean_adj_mat)
        return adj_mat, norm_adj_mat, mean_adj_mat

    def create_adj_mat(self):
        t1 = time()
        adj_mat = sp.dok_matrix((self.n_users + self.n_items, self.n_users + self.n_items), dtype=np.float32)
        self.save_adf=adj_mat
        adj_mat = adj_mat.tolil()
        R = self.R.tolil()
        #self.save_adf=adj_mat

        adj_mat[:self.n_users, self.n_users:] = R
        adj_mat[self.n_users:, :self.n_users] = R.T
        adj_mat = adj_mat.todok()
        print('already create adjacency matrix', adj_mat.shape, time() - t1)

        t2 = time()

        def mean_adj_single(adj):
            # D^-1 * A
            rowsum = np.array(adj.sum(1))

            d_inv = np.power(rowsum, -1).flatten()
            d_inv[np.isinf(d_inv)] = 0.
            d_mat_inv = sp.diags(d_inv)

            norm_adj = d_mat_inv.dot(adj)
            # norm_adj = adj.dot(d_mat_inv)
            print('generate single-normalized adjacency matrix.')
            return norm_adj.tocoo()

        def normalized_adj_single(adj):
            # D^-1/2 * A * D^-1/2
            rowsum = np.array(adj.sum(1))

            d_inv_sqrt = np.power(rowsum, -0.5).flatten()
            d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
            d_mat_inv_sqrt = sp.diags(d_inv_sqrt)

            # bi_lap = adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt)
            bi_lap = d_mat_inv_sqrt.dot(adj).dot(d_mat_inv_sqrt)
            return bi_lap.tocoo()

        def check_adj_if_equal(adj):
            dense_A = np.array(adj.todense())
            degree = np.sum(dense_A, axis=1, keepdims=False)

            temp = np.dot(np.diag(np.power(degree, -1)), dense_A)
            print('check normalized adjacency matrix whether equal to this laplacian matrix.')
            return temp

        norm_adj_mat = mean_adj_single(adj_mat + sp.eye(adj_mat.shape[0]))
        # norm_adj_mat = normalized_adj_single(adj_mat + sp.eye(adj_mat.shape[0]))
        mean_adj_mat = mean_adj_single(adj_mat)

        print('already normalize adjacency matrix', time() - t2)
        return adj_mat.tocsr(), norm_adj_mat.tocsr(), mean_adj_mat.tocsr()

    def negative_pool(self):
        t1 = time()
        for u in self.train_items.keys():
            neg_items = list(set(range(self.n_items)) - set(self.train_items[u]))
            pools = [rd.choice(neg_items) for _ in range(100)]
            self.neg_pools[u] = pools
        print('refresh negative pools', time() - t1)

    def sample(self):
        if self.batch_size <= self.n_users:
            users = rd.sample(self.exist_users, self.batch_size)
        else:
            users = [rd.choice(self.exist_users) for _ in range(self.batch_size)]

        def sample_pos_items_for_u(u, num):
            # sample num pos items for u-th user
            pos_items = self.train_items[u]
            n_pos_items = len(pos_items)
            pos_batch = []
            while True:
                if len(pos_batch) == num:
                    break
                pos_id = np.random.randint(low=0, high=n_pos_items, size=1)[0]
                pos_i_id = pos_items[pos_id]

                if pos_i_id not in pos_batch:
                    pos_batch.append(pos_i_id)
            return pos_batch

        def sample_neg_items_for_u(u, num):
            # sample num neg items for u-th user
            neg_items = []
            while True:
                if len(neg_items) == num:
                    break
                neg_id = np.random.randint(low=0, high=self.n_items,size=1)[0]
                if neg_id not in self.train_items[u] and neg_id not in neg_items:
                    neg_items.append(neg_id)
            return neg_items

        def sample_neg_items_for_u_from_pools(u, num):
            neg_items = list(set(self.neg_pools[u]) - set(self.train_items[u]))
            return rd.sample(neg_items, num)

        pos_items, neg_items = [], []
        for u in users:
            pos_items += sample_pos_items_for_u(u, 1)
            neg_items += sample_neg_items_for_u(u, 1)

        return users, pos_items, neg_items

    def get_num_users_items(self):
        return self.n_users, self.n_items

    def print_statistics(self):
        print('n_users=%d, n_items=%d' % (self.n_users, self.n_items))
        print('user_neighbors=%d, item_neighbors=%d' % (len(self.user_neighbors), len(self.item_neighbors)))
        print('n_interactions=%d' % (self.n_train + self.n_test))
        print('n_train=%d, n_test=%d, sparsity=%.5f' % (self.n_train, self.n_test, (self.n_train + self.n_test)/(self.n_users * self.n_items))) #self.user_neighbors

    def get_sparsity_split(self):
        try:
            split_uids, split_state = [], []
            lines = open(self.path + '/sparsity.split', 'r').readlines()

            for idx, line in enumerate(lines):
                if idx % 2 == 0:
                    split_state.append(line.strip())
                    print(line.strip())
                else:
                    split_uids.append([int(uid) for uid in line.strip().split(' ')])
            print('get sparsity split.')

        except Exception:
            split_uids, split_state = self.create_sparsity_split()
            f = open(self.path + '/sparsity.split', 'w')
            for idx in range(len(split_state)):
                f.write(split_state[idx] + '\n')
                f.write(' '.join([str(uid) for uid in split_uids[idx]]) + '\n')
            print('create sparsity split.')

        return split_uids, split_state

    def create_sparsity_split(self):
        all_users_to_test = list(self.test_set.keys())
        user_n_iid = dict()

        # generate a dictionary to store (key=n_iids, value=a list of uid).
        for uid in all_users_to_test:
            train_iids = self.train_items[uid]
            test_iids = self.test_set[uid]

            n_iids = len(train_iids) + len(test_iids)

            if n_iids not in user_n_iid.keys():
                user_n_iid[n_iids] = [uid]
            else:
                user_n_iid[n_iids].append(uid)
        split_uids = list()

        # split the whole user set into four subset.
        temp = []
        count = 1
        fold = 4
        n_count = (self.n_train + self.n_test)
        n_rates = 0

        split_state = []
        for idx, n_iids in enumerate(sorted(user_n_iid)):
            temp += user_n_iid[n_iids]
            n_rates += n_iids * len(user_n_iid[n_iids])
            n_count -= n_iids * len(user_n_iid[n_iids])

            if n_rates >= count * 0.25 * (self.n_train + self.n_test):
                split_uids.append(temp)

                state = '#inter per user<=[%d], #users=[%d], #all rates=[%d]' %(n_iids, len(temp), n_rates)
                split_state.append(state)
                print(state)

                temp = []
                n_rates = 0
                fold -= 1

            if idx == len(user_n_iid.keys()) - 1 or n_count == 0:
                split_uids.append(temp)

                state = '#inter per user<=[%d], #users=[%d], #all rates=[%d]' % (n_iids, len(temp), n_rates)
                split_state.append(state)
                print(state)



        return split_uids, split_state

class NGCF(nn.Module):
    def __init__(self, n_user, n_item, norm_adj, args):
        super(NGCF, self).__init__()
        self.n_user = n_user
        self.n_item = n_item
        self.device = args.device
        self.emb_size = args.embed_size
        self.batch_size = args.batch_size
        self.node_dropout = args.node_dropout[0]
        self.mess_dropout = args.mess_dropout
        self.batch_size = args.batch_size
        self.user_embeddings_train=None
        self.item_embeddings_train=None
        self.norm_adj = norm_adj
        self.model_A_hat=None
        self.layers = eval(args.layer_size)
        self.decay = eval(args.regs)[0]
        self.use_attributes=args.use_attributes
        self.retain_attributes=args.retain_attributes
        self.user_neighbors = args.user_neighbors
        self.item_neighbors = args.item_neighbors
        self.use_attn=args.attn
        print('**** Attn check attn in class *******',self.use_attn)
        """
        *********************************************************
        Init the weight of user-item.
        For including attributes its sufficnet to load features/attributes
        """
        #self.embedding_dict, self.weight_dict = self.init_weight()
        print('In case  where attributes of users are used , initialized user embeddings would be appear as one hot encoded otherwise as Random')
        self.embedding_dict, self.weight_dict = self.init_weight() # Random
        print('input_user_features_sample',self.embedding_dict['user_emb'][0,:])
        print('-----------------------------')
        print('\n')
        # self.embedding_user = torch.nn.Embedding(
        #     num_embeddings=self.n_user, embedding_dim=self.emb_size)
        # self.embedding_item = torch.nn.Embedding(
        #     num_embeddings=self.n_item, embedding_dim=self.emb_size)
        # tar=np.load(lgcn_data1+'user_feat.npy')
        # war=np.load(lgcn_data1+'item_feat.npy')


        """
        *********************************************************
        Get sparse adj.
        """
        self.sparse_norm_adj = self._convert_sp_mat_to_sp_tensor(self.norm_adj).to(self.device)


    def init_weight(self):
      # === Weight Initialization ===
      initializer = nn.init.xavier_uniform_

      # === Embedding Initialization ===
      embedding_dict = nn.ParameterDict({
          'user_emb': nn.Parameter(initializer(torch.empty(self.n_user, self.emb_size))),
          'item_emb': nn.Parameter(initializer(torch.empty(self.n_item, self.emb_size)))
      })

      # === Optional: Use attribute-based embeddings ===
      if self.use_attributes:
          print('*** user/item embeddings are initialized with features/attributes ***')
          tar = np.load(save_path + 'user_features.npy')
          war = np.load(save_path + 'item_features.npy')
          embedding_dict['user_emb'].data = torch.FloatTensor(tar)
          embedding_dict['item_emb'].data = torch.FloatTensor(war)

          if self.retain_attributes:
              print('*** embeddings frozen ***')
              embedding_dict['user_emb'].requires_grad = False
              embedding_dict['item_emb'].requires_grad = False
          else:
              print('*** embeddings trainable ***')

      # === Message Passing Weights ===
      weight_dict = nn.ParameterDict()
      layers = [self.emb_size] + self.layers
      for k in range(len(self.layers)):
          weight_dict.update({
              f'W_gc_{k}': nn.Parameter(initializer(torch.empty(layers[k], layers[k+1]))),
              f'b_gc_{k}': nn.Parameter(initializer(torch.empty(1, layers[k+1]))),
              f'W_bi_{k}': nn.Parameter(initializer(torch.empty(layers[k], layers[k+1]))),
              f'b_bi_{k}': nn.Parameter(initializer(torch.empty(1, layers[k+1]))),
          })
          att_in_dim = 2 * layers[k]         # [center || neighbor]
          att_hidden_dim = layers[k+1]       # project to match next layer

          weight_dict[f'W_att_{k}'] = nn.Parameter(initializer(torch.empty(att_in_dim, att_hidden_dim)))
          weight_dict[f'V_att_{k}'] = nn.Parameter(initializer(torch.empty(att_hidden_dim, 1)))

          print(f"DEBUG W_att_{k} shape: {att_in_dim} → {att_hidden_dim}")
      return embedding_dict, weight_dict


    def _convert_sp_mat_to_sp_tensor(self, X):
        coo = X.tocoo()
        i = torch.LongTensor([coo.row, coo.col])
        v = torch.from_numpy(coo.data).float()
        return torch.sparse.FloatTensor(i, v, coo.shape)

    def sparse_dropout(self, x, rate, noise_shape):
        random_tensor = 1 - rate
        random_tensor += torch.rand(noise_shape).to(x.device)
        dropout_mask = torch.floor(random_tensor).type(torch.bool)
        i = x._indices()
        v = x._values()

        i = i[:, dropout_mask]
        v = v[dropout_mask]

        out = torch.sparse.FloatTensor(i, v, x.shape).to(x.device)
        return out * (1. / (1 - rate))

    def create_bpr_loss(self, users, pos_items, neg_items):
        pos_scores = torch.sum(torch.mul(users, pos_items), axis=1)
        neg_scores = torch.sum(torch.mul(users, neg_items), axis=1)

        maxi = nn.LogSigmoid()(pos_scores - neg_scores)

        mf_loss = -1 * torch.mean(maxi)

        # cul regularizer
        regularizer = (torch.norm(users) ** 2
                       + torch.norm(pos_items) ** 2
                       + torch.norm(neg_items) ** 2) / 2
        emb_loss = self.decay * regularizer / self.batch_size

        return mf_loss + emb_loss, mf_loss, emb_loss

    def rating(self, u_g_embeddings, pos_i_g_embeddings):
        return torch.matmul(u_g_embeddings, pos_i_g_embeddings.t())

    def _aggx(self, center_ids, ego_embeddings, k,is_user=True):
      device = ego_embeddings.device
      batch_size = center_ids.shape[0]
      dim = ego_embeddings.shape[1]
      attn_k = self.user_neighbors.shape[1]  # assumes padded
      center_ids = center_ids.clamp(max=self.n_item - 1)# new addiion
      center_ids = center_ids.to(device)  # 🛠️ Ensure center_ids is on correct device

      if is_user:
          neighbor_ids = self.user_neighbors[center_ids]            # (B, K)
          center_embeddings = ego_embeddings[center_ids]               # (B, D)
          neighbor_embeddings = ego_embeddings[self.n_user + neighbor_ids]  # (B, K, D)
      else:
          neighbor_ids = self.item_neighbors[center_ids]           # (B, K)
          center_embeddings = ego_embeddings[self.n_user + center_ids] # (B, D)
          neighbor_embeddings = ego_embeddings[neighbor_ids]           # (B, K, D)

      center_expanded = center_embeddings.unsqueeze(1).repeat(1, attn_k, 1)  # (B, K, D)
      concat = torch.cat([center_expanded, neighbor_embeddings], dim=2)     # (B, K, 2D)
      #print('here-atten',k,is_user,concat.shape,self.weight_dict[f'W_att_{k}'].shape)
      flat = concat.view(batch_size * attn_k, -1)                            # (B*K, 2D)
      scores = torch.tanh(flat @ self.weight_dict[f'W_att_{k}'])                 # (B*K, D)
      scores = scores @ self.weight_dict[f'V_att_{k}']                           # (B*K, 1)
      scores = scores.view(batch_size, 1, attn_k)                           # (B, 1, K)
      weights = torch.softmax(scores, dim=2)                                # (B, 1, K)

      agg_neighbors = torch.bmm(weights, neighbor_embeddings).squeeze(1)    # (B, D)
      return agg_neighbors
      



# === Part 3: Forward Pass ===
 
    def _agg(self, center_ids, ego_embeddings, k, is_user=True,debug=False):
        device = ego_embeddings.device
        batch_size = center_ids.shape[0]
        dim = ego_embeddings.shape[1]
    
        # Determine attention neighborhood size from preprocessed neighbors
        attn_k = self.user_neighbors.shape[1] if is_user else self.item_neighbors.shape[1]
    
        # Ensure center_ids are valid and on correct device
        center_ids = center_ids.to(device)
        if is_user:
            center_ids = center_ids.clamp(0, self.n_user - 1)
            neighbor_ids = self.user_neighbors[center_ids].to(device)  # (B, K)
            center_embeddings = ego_embeddings[center_ids]             # (B, D)
            neighbor_indices = self.n_user + neighbor_ids              # shift item indices
            neighbor_indices = neighbor_indices.clamp(0, ego_embeddings.shape[0] - 1)
            neighbor_embeddings = ego_embeddings[neighbor_indices]     # (B, K, D)
        else:
            center_ids = center_ids.clamp(0, self.n_item - 1)
            neighbor_ids = self.item_neighbors[center_ids].to(device)  # (B, K)
            center_indices = self.n_user + center_ids
            center_indices = center_indices.clamp(0, ego_embeddings.shape[0] - 1)
            center_embeddings = ego_embeddings[center_indices]         # (B, D)
            neighbor_ids = neighbor_ids.clamp(0, self.n_item - 1)
            neighbor_embeddings = ego_embeddings[neighbor_ids]         # (B, K, D)
    
        # Repeat center for concat
        center_expanded = center_embeddings.unsqueeze(1).repeat(1, attn_k, 1)  # (B, K, D)
    
        # 🔍 Debug prints for tracing index problems
        # if debug:
        #     print(f"\n🧠 DEBUG @ Layer {k}, is_user={is_user}")
        #     print("📐 center_ids[:10]:", center_ids[:10])
        #     print("📐 neighbor_ids[:3]:", neighbor_ids[:3])
        #     print("🔢 ego_embeddings.shape:", ego_embeddings.shape)
        #     if not is_user:
        #         print("🔢 max center index used:", center_indices.max().item())
        #     print("🔢 max neighbor index used:", neighbor_ids.max().item())
        #     print("🧱 center_embeddings shape:", center_embeddings.shape)
        #     print("🧱 neighbor_embeddings shape:", neighbor_embeddings.shape)
        #     print("🧱 center_expanded shape:", center_expanded.shape)
        
        #     if is_user:
        #         bad = (self.n_user + neighbor_ids) >= ego_embeddings.shape[0]
        #         if bad.any():
        #             print("❌ Invalid user→item neighbor index found!")
        #             print("Offending max idx:", (self.n_user + neighbor_ids)[bad].max().item())
        #     else:
        #         bad_c = center_indices >= ego_embeddings.shape[0]
        #         bad_n = neighbor_ids >= self.n_item
        #         if bad_c.any():
        #             print("❌ Invalid item center index:", center_indices[bad_c])
        #         if bad_n.any():
        #             print("❌ Invalid item neighbor index:", neighbor_ids[bad_n])
    
        # Attention mechanism
        concat = torch.cat([center_expanded, neighbor_embeddings], dim=2)  # (B, K, 2D)
        flat = concat.view(batch_size * attn_k, -1)                         # (B*K, 2D)
    
        W_att = self.weight_dict[f'W_att_{k}'].to(device)
        V_att = self.weight_dict[f'V_att_{k}'].to(device)
    
        scores = torch.tanh(flat @ W_att) @ V_att                           # (B*K, 1)
        scores = scores.view(batch_size, 1, attn_k)                         # (B, 1, K)
        weights = torch.softmax(scores, dim=2)                              # (B, 1, K)
    
        agg_neighbors = torch.bmm(weights, neighbor_embeddings).squeeze(1)  # (B, D)
        return agg_neighbors

    def forwardx(self, users, pos_items, neg_items, drop_flag=True):
        A_hat = self.sparse_dropout(self.sparse_norm_adj,
                                    self.node_dropout,
                                    self.sparse_norm_adj._nnz()) if drop_flag else self.sparse_norm_adj
        self.model_A_hat = A_hat

        ego_embeddings = torch.cat([self.embedding_dict['user_emb'],
                                    self.embedding_dict['item_emb']], dim=0).type(torch.float32) #keep fix
        expected_nodes = self.n_user + self.n_item
        if ego_embeddings.shape[0] != expected_nodes:
            print(f"⚠️ Trimming initial ego_embeddings: {ego_embeddings.shape[0]} → {expected_nodes}")
            ego_embeddings = ego_embeddings[:expected_nodes]

        all_embeddings = [ego_embeddings]
        #print(ego_embeddings.device,'device')
        for k in range(len(self.layers)):
            user_ids = torch.arange(self.n_user, device=ego_embeddings.device)
            item_ids = torch.arange(self.n_item, device=ego_embeddings.device)
            #print('using attn',self.use_attn)
            if self.use_attn:
              #using attn
              #print('hcekc',self.use_attn)  
              user_agg = self._agg(user_ids, ego_embeddings,k ,is_user=True)
              item_agg = self._agg(item_ids, ego_embeddings,k, is_user=False)
              expected_nodes = self.n_user + self.n_item  
              ego_embeddings = torch.cat([user_agg, item_agg], dim=0)
              if ego_embeddings.shape[0] != expected_nodes:
                print(f"⚠️ Adjusting ego_embeddings size: {ego_embeddings.shape[0]} → {expected_nodes}")
                ego_embeddings = ego_embeddings[:expected_nodes]

            side_embeddings = torch.sparse.mm(A_hat, ego_embeddings)

            sum_embeddings = torch.matmul(side_embeddings, self.weight_dict[f'W_gc_{k}']) \
                            + self.weight_dict[f'b_gc_{k}']

            bi_embeddings = torch.mul(ego_embeddings, side_embeddings)
            bi_embeddings = torch.matmul(bi_embeddings, self.weight_dict[f'W_bi_{k}']) \
                            + self.weight_dict[f'b_bi_{k}']

            ego_embeddings = F.leaky_relu(sum_embeddings + bi_embeddings, negative_slope=0.2)
            ego_embeddings = F.dropout(ego_embeddings, p=self.mess_dropout[k], training=self.training)
            norm_embeddings = F.normalize(ego_embeddings, p=2, dim=1)

            all_embeddings.append(norm_embeddings)

        all_embeddings = torch.cat(all_embeddings, dim=1)
        u_g_embeddings = all_embeddings[:self.n_user, :]
        i_g_embeddings = all_embeddings[self.n_user:, :]

        u_g_embeddings = u_g_embeddings[users, :]
        pos_i_g_embeddings = i_g_embeddings[pos_items, :]
        neg_i_g_embeddings = i_g_embeddings[neg_items, :]

        return u_g_embeddings, pos_i_g_embeddings, neg_i_g_embeddings

    def forward(self, users, pos_items, neg_items, drop_flag=True):
    # === Step 1: Sparse dropout ===
        A_hat = self.sparse_dropout(self.sparse_norm_adj,
                                    self.node_dropout,
                                    self.sparse_norm_adj._nnz()) if drop_flag else self.sparse_norm_adj
        self.model_A_hat = A_hat
    
        # === Step 2: Initial Embedding Setup ===
        ego_embeddings = torch.cat([
            self.embedding_dict['user_emb'],
            self.embedding_dict['item_emb']
        ], dim=0).type(torch.float32)  # Ensure float32
    
        expected_nodes = self.n_user + self.n_item
        if ego_embeddings.shape[0] != expected_nodes:
            print(f"⚠️ Trimming initial ego_embeddings: {ego_embeddings.shape[0]} → {expected_nodes}")
            ego_embeddings = ego_embeddings[:expected_nodes]
    
        all_embeddings = [ego_embeddings]
    
        # === Step 3: Layer-wise Propagation ===
        for k in range(len(self.layers)):
            user_ids = torch.arange(self.n_user, device=ego_embeddings.device)
            item_ids = torch.arange(self.n_item, device=ego_embeddings.device)
    
            # --- Optional Attention Aggregation ---
            if self.use_attn:
                user_agg = self._agg(user_ids, ego_embeddings, k, is_user=True)
                item_agg = self._agg(item_ids, ego_embeddings, k, is_user=False)
                ego_embeddings = torch.cat([user_agg, item_agg], dim=0)
    
            # ✅ Trim ego_embeddings for safety (works even without attention)
            if ego_embeddings.shape[0] != expected_nodes:
                print(f"⚠️ Trimming ego_embeddings at layer {k}: {ego_embeddings.shape[0]} → {expected_nodes}")
                ego_embeddings = ego_embeddings[:expected_nodes]
    
            # --- Message Passing ---
            side_embeddings = torch.sparse.mm(A_hat, ego_embeddings)
    
            # Transformed sum message
            sum_embeddings = torch.matmul(side_embeddings, self.weight_dict[f'W_gc_{k}']) \
                             + self.weight_dict[f'b_gc_{k}']
    
            # Transformed bi interaction
            bi_embeddings = torch.mul(ego_embeddings, side_embeddings)
            bi_embeddings = torch.matmul(bi_embeddings, self.weight_dict[f'W_bi_{k}']) \
                            + self.weight_dict[f'b_bi_{k}']
    
            # LeakyReLU + Dropout + Normalize
            ego_embeddings = F.leaky_relu(sum_embeddings + bi_embeddings, negative_slope=0.2)
            ego_embeddings = F.dropout(ego_embeddings, p=self.mess_dropout[k], training=self.training)
            norm_embeddings = F.normalize(ego_embeddings, p=2, dim=1)
    
            all_embeddings.append(norm_embeddings)
    
        # === Step 4: Final Concatenation ===
        all_embeddings = torch.cat(all_embeddings, dim=1)
        u_g_embeddings = all_embeddings[:self.n_user, :]
        i_g_embeddings = all_embeddings[self.n_user:, :]
    
        # === Step 5: Gather Output Embeddings for BPR Loss ===
        u_g_embeddings = u_g_embeddings[users, :]
        pos_i_g_embeddings = i_g_embeddings[pos_items, :]
        neg_i_g_embeddings = i_g_embeddings[neg_items, :]
    
        return u_g_embeddings, pos_i_g_embeddings, neg_i_g_embeddings

    # def forward(self, users, pos_items, neg_items, drop_flag=True):

    #     A_hat = self.sparse_dropout(self.sparse_norm_adj,
    #                                 self.node_dropout,
    #                                 self.sparse_norm_adj._nnz()) if drop_flag else self.sparse_norm_adj
    #     ego_embeddings = torch.cat([self.embedding_dict['user_emb'],
    #                                     self.embedding_dict['item_emb']], 0)
    #     ##### Other experiments
    #     """
    #     *********************************************************
    #     Experiments where laplacian matrix is modified during inference only
    #     """
    #     self.model_A_hat=A_hat
    #     ##### my changes
    #     all_embeddings = [ego_embeddings]
    #     #print(A_hat.shape,ego_embeddings.shape)
    #     for k in range(len(self.layers)):
    #         side_embeddings = torch.sparse.mm(A_hat, ego_embeddings) #### This step in forward pass requires A_hat modifications

    #         # transformed sum messages of neighbors.
    #         sum_embeddings = torch.matmul(side_embeddings, self.weight_dict['W_gc_%d' % k]) \
    #                                          + self.weight_dict['b_gc_%d' % k]

    #         # bi messages of neighbors.
    #         # element-wise product
    #         bi_embeddings = torch.mul(ego_embeddings, side_embeddings)
    #         # transformed bi messages of neighbors.
    #         bi_embeddings = torch.matmul(bi_embeddings, self.weight_dict['W_bi_%d' % k]) \
    #                                         + self.weight_dict['b_bi_%d' % k]

    #         # non-linear activation.
    #         ego_embeddings = nn.LeakyReLU(negative_slope=0.2)(sum_embeddings + bi_embeddings)

    #         # message dropout.
    #         ego_embeddings = nn.Dropout(self.mess_dropout[k])(ego_embeddings)

    #         # normalize the distribution of embeddings.
    #         norm_embeddings = F.normalize(ego_embeddings, p=2, dim=1)

    #         all_embeddings += [norm_embeddings]

    #     all_embeddings = torch.cat(all_embeddings, 1)
    #     u_g_embeddings = all_embeddings[:self.n_user, :]
    #     i_g_embeddings = all_embeddings[self.n_user:, :]
    #     self.user_embeddings_train=u_g_embeddings
    #     self.item_embeddings_train=i_g_embeddings
    #     """
    #     *********************************************************
    #     look up.
    #     """
    #     u_g_embeddings = u_g_embeddings[users, :]
    #     pos_i_g_embeddings = i_g_embeddings[pos_items, :]
    #     neg_i_g_embeddings = i_g_embeddings[neg_items, :]

    #     return u_g_embeddings, pos_i_g_embeddings, neg_i_g_embeddings

def train(args, model):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)

    optimizer = optim.Adam(model.parameters(), lr=args.lr)

    total_losses, mf_losses, emb_losses = [], [], []

    if args.use_attributes:
        if args.retain_attributes:
            model_type = 'u_embedding_initialization_user_feature/attributes_used_and_frozen'
        else:
            model_type = 'u_embedding_initialization_user_feature/attributes_used_but_updated'
    else:
        model_type = 'u_embedding_initialization_user_feature/attributes_are_notused_randomly_initialized'

    results = []
    #for epoch in range(args.epoch):
    for epoch in tqdm(range(args.epoch), desc="📅 Training Epochs"):

        epoch_loss, epoch_mf_loss, epoch_emb_loss = 0., 0., 0.
        n_batch = data_generator.n_train // args.batch_size + 1

        for idx in range(n_batch):
            users, pos_items, neg_items = data_generator.sample()
            users = torch.tensor(users).to(device)
            pos_items = torch.tensor(pos_items).to(device)
            neg_items = torch.tensor(neg_items).to(device)

            u_g_embeddings, pos_i_g_embeddings, neg_i_g_embeddings = model(
                users, pos_items, neg_items, drop_flag=args.node_dropout_flag)

            batch_loss, batch_mf_loss, batch_emb_loss = model.create_bpr_loss(
                u_g_embeddings, pos_i_g_embeddings, neg_i_g_embeddings)

            optimizer.zero_grad()
            batch_loss.backward()
            optimizer.step()

            epoch_loss += batch_loss.item()
            epoch_mf_loss += batch_mf_loss.item()
            epoch_emb_loss += batch_emb_loss.item()

        total_losses.append(epoch_loss)
        mf_losses.append(epoch_mf_loss)
        emb_losses.append(epoch_emb_loss)

        print(f"Epoch {epoch} completed: Total Loss={epoch_loss:.4f}, MF Loss={epoch_mf_loss:.4f}, Emb Loss={epoch_emb_loss:.4f}")
        results.append((model_type, epoch, round(epoch_loss, 4)))

    # Plot losses
    epochs = range(args.epoch)
    plt.figure(figsize=(10,6))
    #plt.plot(epochs, total_losses, label='Total Loss')
    plt.plot(epochs, mf_losses, label='Loss')
    #plt.plot(epochs, emb_losses, label='Embedding Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training Losses over Epochs')
    plt.legend()
    plt.grid()
    plt.show()

    return results

def str2bool(v):
    if isinstance(v, bool):
        return v
    return v.lower() in ("yes", "true", "t", "1")

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('--use_attributes', type=str2bool, default=False, help='Use pretrained user/item attributes')
    parser.add_argument('--retain_attributes', type=str2bool, default=True, help='Freeze pretrained embeddings during training')
    parser.add_argument('--attn', type=str2bool, default=False, help='Enable attention-based aggregation')
    parser.add_argument('--epoch', type=int, default=10, help='Number of training epochs')
    return parser.parse_args()
    #return parser.parse_args()
def test_one_user(x):
    # user u's ratings for user u
    rating = x[0]
    #uid
    u = x[1]
    #user u's items in the training set
    try:
        training_items = data_generator.train_items[u]
    except Exception:
        training_items = []
    #user u's items in the test set
    user_pos_test = data_generator.test_set[u]

    all_items = set(range(ITEM_NUM))

    test_items = list(all_items - set(training_items))

    if args.test_flag == 'part':
        r, auc = ranklist_by_heapq(user_pos_test, test_items, rating, Ks)
    else:
        r, auc = ranklist_by_sorted(user_pos_test, test_items, rating, Ks)

    return get_performance(user_pos_test, r, auc, Ks)


def test(model, users_to_test, drop_flag=False, batch_test_flag=False):
    import multiprocessing
    cores = multiprocessing.cpu_count() // 2  # Use half the cores to be safe
    pool = multiprocessing.Pool(cores)
    Ks = [10]
    result = {'precision': np.zeros(len(Ks)), 'recall': np.zeros(len(Ks)), 'ndcg': np.zeros(len(Ks)),
              'hit_ratio': np.zeros(len(Ks)), 'auc': 0.}

    pool = multiprocessing.Pool(cores)

    u_batch_size = BATCH_SIZE * 2
    i_batch_size = BATCH_SIZE

    test_users = users_to_test
    n_test_users = len(test_users)
    n_user_batchs = n_test_users // u_batch_size + 1

    count = 0

    for u_batch_id in range(n_user_batchs):
        start = u_batch_id * u_batch_size
        end = (u_batch_id + 1) * u_batch_size

        user_batch = test_users[start: end]

        if batch_test_flag:
            # batch-item test
            n_item_batchs = ITEM_NUM // i_batch_size + 1
            rate_batch = np.zeros(shape=(len(user_batch), ITEM_NUM))

            i_count = 0
            for i_batch_id in range(n_item_batchs):
                i_start = i_batch_id * i_batch_size
                i_end = min((i_batch_id + 1) * i_batch_size, ITEM_NUM)

                item_batch = range(i_start, i_end)

                if drop_flag == False:
                    u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
                                                                  item_batch,
                                                                  [],
                                                                  drop_flag=False)
                    i_rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()
                else:
                    u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
                                                                  item_batch,
                                                                  [],
                                                                  drop_flag=True)
                    i_rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()

                rate_batch[:, i_start: i_end] = i_rate_batch
                i_count += i_rate_batch.shape[1]

            assert i_count == ITEM_NUM

        else:
            # all-item test
            item_batch = range(ITEM_NUM)

            if drop_flag == False:
                u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
                                                              item_batch,
                                                              [],
                                                              drop_flag=False)
                rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()
            else:
                u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch,
                                                              item_batch,
                                                              [],
                                                              drop_flag=True)
                rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()

        user_batch_rating_uid = zip(rate_batch.numpy(), user_batch)
        batch_result = pool.map(test_one_user, user_batch_rating_uid)
        count += len(batch_result)

        for re in batch_result:
            result['precision'] += re['precision']/n_test_users
            result['recall'] += re['recall']/n_test_users
            result['ndcg'] += re['ndcg']/n_test_users
            result['hit_ratio'] += re['hit_ratio']/n_test_users
            result['auc'] += re['auc']/n_test_users


    assert count == n_test_users
    pool.close()
    return result

if __name__ == "__main__":
    print('___ Neural Graph With Attention_____ ')
    def test(model, users_to_test, drop_flag=False, batch_test_flag=False):
        cores = multiprocessing.cpu_count() // 2
        pool = multiprocessing.Pool(cores)
    
        Ks = [10]
        BATCH_SIZE = args.batch_size
        ITEM_NUM = data_generator.n_items
    
        result = {'precision': np.zeros(len(Ks)), 'recall': np.zeros(len(Ks)), 'ndcg': np.zeros(len(Ks)),
                  'hit_ratio': np.zeros(len(Ks)), 'auc': 0.}
    
        u_batch_size = BATCH_SIZE * 2
        i_batch_size = BATCH_SIZE
    
        test_users = users_to_test
        n_test_users = len(test_users)
        n_user_batchs = n_test_users // u_batch_size + 1
    
        count = 0
    
        for u_batch_id in range(n_user_batchs):
            start = u_batch_id * u_batch_size
            end = (u_batch_id + 1) * u_batch_size
            user_batch = test_users[start:end]
    
            if len(user_batch) == 0:
                continue
    
            item_batch = range(ITEM_NUM)
    
            if not drop_flag:
                u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch, item_batch, [], drop_flag=False)
            else:
                u_g_embeddings, pos_i_g_embeddings, _ = model(user_batch, item_batch, [], drop_flag=True)
    
            rate_batch = model.rating(u_g_embeddings, pos_i_g_embeddings).detach().cpu()
            user_batch_rating_uid = zip(rate_batch.numpy(), user_batch)
    
            batch_result = pool.map(test_one_user, user_batch_rating_uid)
            count += len(batch_result)
    
            for re in batch_result:
                result['precision'] += re['precision'] / n_test_users
                result['recall'] += re['recall'] / n_test_users
                result['ndcg'] += re['ndcg'] / n_test_users
                result['hit_ratio'] += re['hit_ratio'] / n_test_users
                result['auc'] += re['auc'] / n_test_users
    
        assert count == n_test_users
        pool.close()
        pool.join()  # ✅ add this to avoid the 'NoneType' error
        return result

    path='/content/drive/MyDrive/MovieLens_100K/'
    save_path = '/content/drive/MyDrive/MovieLens_100K/'
    model_path='/content/drive/MyDrive/CSPROJ/'
    argssys = parse_args()    
    class vars():
      def __init__(self):
          self.weights_path='model/'
          self.data_path=path
          self.proj_path=''
          self.dataset=''#'D4'
          self.pretrain=0
          self.verbose=1
          self.epoch=30
          self.embed_size=52#375#375 #419  #### 128 #dimenions of input feature vector ***
          self.layer_size='[64,32,16]' #### hidden dimesions of convolutions ***
          self.batch_size=32
          self.regs='[1e-5]'
          self.lr=0.0005
          self.model_type='ngcf'
          self.adj_type='norm'
          self.gpu_id=0
          self.node_dropout_flag=0
          self.node_dropout='[0.1]'
          self.mess_dropout='[0.1,0.1,0.1]'
          #self.Ks='[20, 40, 60, 80, 100]'
          self.Ks='[10]' #'[5, 10, 20]'
          self.save_flag=1
          self.test_flag='part'
          self.report=0
          self.use_attributes=True
          self.retain_attributes=True
          self.user_neighbors=None
          self.item_neighbors=None
          self.attn=False
          self.device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    args=vars()
    args.use_attributes=argssys.use_attributes
    args.retain_attributes=argssys.retain_attributes
    args.attn=argssys.attn
    args.epoch=argssys.epoch
    #print(eval(args.Ks))
    print(f"\n🛠️ Model Config → 🔘 use_attributes: {args.use_attributes} | 🔒 retain_attributes: {args.retain_attributes} | ✨ attn: {args.attn} | 📅 epochs: {args.epoch}\n")


    tar=np.load(save_path+'user_features.npy', allow_pickle=True)
    war=np.load(save_path+'item_features.npy', allow_pickle=True)
    print(tar.shape,war.shape)
    cores = multiprocessing.cpu_count() // 2

    #args = parse_args()
    Ks = eval(args.Ks)

    data_generator = Data(path=args.data_path + args.dataset, batch_size=args.batch_size)
    USR_NUM, ITEM_NUM = data_generator.n_users, data_generator.n_items
    N_TRAIN, N_TEST = data_generator.n_train, data_generator.n_test
    BATCH_SIZE = args.batch_size
    args.user_neighbors=data_generator.user_neighbors.to(args.device)
    args.item_neighbors=data_generator.item_neighbors.to(args.device)

    adj_mat, norm_adj_mat, _ = data_generator.get_adj_mat()
    GPU = torch.cuda.is_available()
    # args.use_attributes=False
    # args.retain_attributes=False
    # args.node_dropout='[0.1]'
    # args.mess_dropout='[0.1,0.1,0.1]'
    args.device = torch.device('cuda' if GPU else "cpu")
    print(GPU,args.device)
    plain_adj, norm_adj, mean_adj = data_generator.get_adj_mat()
    args.node_dropout = eval(args.node_dropout)
    args.mess_dropout = eval(args.mess_dropout)
    cores = multiprocessing.cpu_count() // 2

    #args = parse_args()
    Ks = eval(args.Ks)

    # args.use_attributes=False
    # args.retain_attributes=True
    # args.epoch=50
    model = NGCF(data_generator.n_users,
                    data_generator.n_items,
                    norm_adj,
                    args).to(args.device)
    res=train(args,model)
    fname=model_path+'Result_trainloss_'+ str(args.use_attributes)+'_'+str(args.retain_attributes)+'_'+str(args.attn)+'_'+str(args.epoch)+'.pkl'
    print(fname)
    with open(fname, 'wb') as f:
      pickle.dump(res, f)
    result = {'precision': np.zeros(len(Ks)), 'recall': np.zeros(len(Ks)), 'ndcg': np.zeros(len(Ks)),
          'hit_ratio': np.zeros(len(Ks)), 'auc': 0.}
    users_to_test = list(data_generator.test_set.keys())
    pool = multiprocessing.Pool(cores)

    u_batch_size = BATCH_SIZE * 2
    i_batch_size = BATCH_SIZE

    test_users = users_to_test
    n_test_users = len(test_users)
    n_user_batchs = n_test_users // u_batch_size + 1
    print(cores,u_batch_size,i_batch_size,n_test_users,n_user_batchs)
    ret = test(model, users_to_test, drop_flag=False)
    print('Validation Metric',ret['ndcg'])
    gname=model_path+'Result_valmetric_'+ str(args.use_attributes)+'_'+str(args.retain_attributes)+'_'+str(args.attn)+'_'+str(args.epoch)+'.pkl'
    print(gname)
    with open(gname, 'wb') as f:
      pickle.dump(ret['ndcg'], f)
    print('-------------sucessful Run-----------')